### PR TITLE
Add support for importing Amazon Transcribe JSON

### PR DESCRIPTION
**Pull request by jarrettyeo**
addresses #146

### CODE REVIEW

**Comment by jarrettyeo** [comment]
Yes @maboa please merge, thanks!

**Comment by maboa** [comment]
Sure. Can you please sign this Contributors License Agreement https://hyperaud.io/cla/

Thanks! :)

**Comment by maboa** [comment]
@jarrettyeo Just waiting for you to sign the CLA (https://hyperaud.io/cla/). Let me know if you have issues with it. Thanks!

**Comment by maboa** [comment]
Reluctantly closing this for now, due to lack of response.

**Pull request closed without merging**
